using System.IO;
using Content.Client.FileManagment;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChatEntryControl : BoxContainer
{
    [Dependency] private readonly IClyde _clyde = default!;
    [Dependency] private readonly FileManager _fileManager = default!;
    
    public ChatEntryControl()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    public void SetUser(UserComponent userComponent)
    {
        Nickname.Text = $"[color=#777777][bold]{userComponent.UserName}[/bold][color]";
    }

    public void HideChatInfo()
    {
        ChatInfo.Visible = false;
    }

    public void SetMessage(ChatEntry message)
    {
        ChatEntryInfo.Text = $"[color=#555555]{message.SendTime}[/color]";

        if (message.File != null)
        {
            _fileManager.GetFile(message.File.Value, OnFileLoaded);
        }
        
        if(message.Message is null) return;
        MessageField.Text = message.Message;
    }

    private void OnFileLoaded(byte[] data)
    {
        using var memoryStream = new MemoryStream(data);
        var texture = _clyde.LoadTextureFromPNGStream(memoryStream);
        var textureControl = new TextureRect()
        {
            Texture = texture, MaxWidth = 200, MaxHeight = 200, Stretch = TextureRect.StretchMode.KeepAspectCentered
        };
        FileContainer.AddChild(textureControl);
    }
}