using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Chat.Controls;

[GenerateTypedNameReferences]
public sealed partial class ChatEntryControl : BoxContainer
{
    public ChatEntryControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void SetUser(UserComponent userComponent)
    {
        if (FormattedMessage.TryFromMarkup($"[color=#777777][bold]{userComponent.UserName}[/bold][color]", out var formattedMessage))
            Nickname.SetMessage(formattedMessage);
        else
            Nickname.Text = userComponent.UserName;
        
        AvatarIcon.TexturePath = "/Textures/default_icon.png";
    }

    public void SetMessage(ChatEntry message)
    {
        if (FormattedMessage.TryFromMarkup(message.Message, out var formattedMessage))
            MessageField.SetMessage(formattedMessage);
        else
            MessageField.Text = message.Message;
        
        ChatEntryInfo.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color=#555555]{message.SendTime}[/color]"));
    }
}