using Content.Client.Chat;
using Content.Client.Chat.Controllers;
using Content.Client.Chat.Controls;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyUI : UIScreen, IChatHandler
{
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    
    private SortedDictionary<DateTime, ChatEntry> _chatEntries = new();
    private readonly List<(Button, Action<BaseButton.ButtonEventArgs>)> _channelListBtns = [];
    
    public LobbyUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(RootContainer, LayoutPreset.Wide);
        SendButton.OnPressed += SendButtonOnOnPressed;
    }

    private void SendButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        _entitySystemManager.GetEntitySystem<ChatSystem>().Send(TextField.Text);
        TextField.Clear();
    }

    private BaseButton? _selectedButton;

    public void SetListChannels(IEnumerable<EntityUid> channels)
    {
        foreach (var (btn,ev) in _channelListBtns)
        {
            btn.OnPressed -= ev;
        }
        
        ChatSelectContainer.Children.Clear();
        
        foreach (var channel in channels)
        {
            if (!_entityManager.TryGetComponent<ChatChannelComponent>(channel, out var channelComponent))
            {
                Log.Error($"Channel {channel} not found");
                continue;
            }

            Action<BaseButton.ButtonEventArgs> action = btn =>
            {
                if(btn.Button.Equals(_selectedButton)) 
                    return;
                
                _entitySystemManager.GetEntitySystem<ChatSystem>().SendSelectedChannel(channel);

                _selectedButton?.Disabled = false;
                _selectedButton = btn.Button;
                _selectedButton.Disabled = true;
            };

            var btn = new Button()
            {
                Text = channelComponent.ChannelName, StyleClasses = { "chat-select" }
            };
            btn.OnPressed += action;
            
            _channelListBtns.Add((btn, action));
            ChatSelectContainer.AddChild(btn);
        }
    }
    
    public void AddMessage(ChatEntry chatEntry)
    {
        _chatEntries.Add(chatEntry.SendTime, chatEntry);
        
        ChatBox.Children.Clear();
        foreach (var entry in _chatEntries)
        {
            AddMessageInternal(entry.Value);
        }
    }

    private void AddMessageInternal(ChatEntry chatEntry)
    {
        if (chatEntry.Sender is not null &&
            _entityManager.TryGetComponent<UserComponent>(_entityManager.GetEntity(chatEntry.Sender.Value),
                out var userComponent))
        {
            var entry = new ChatEntryControl();
            entry.SetUser(userComponent);
            entry.SetMessage(chatEntry);
            ChatBox.Children.Add(entry);
        }
        else
        {
            var richText = new RichTextLabel();
            richText.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color=#555555]{chatEntry.Message}[/Color]"));
            ChatBox.Children.Add(richText);
        }
    }

    public void Clear()
    {
        ChatBox.Children.Clear();
        _chatEntries.Clear();
    }

    public void SetLocalUsername(string name)
    {
        CurrentUserLabel.Text = "Hello," + name;
    }
}