using System.IO;
using Content.Client.Chat;
using Content.Client.Chat.Controllers;
using Content.Client.Chat.Controls;
using Content.Shared.Chat;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.ContentPack;
using Robust.Shared.Utility;

namespace Content.Client.Lobby;

[GenerateTypedNameReferences]
public sealed partial class LobbyUI : UIScreen, IChatHandler
{
    [Dependency] private readonly IEntitySystemManager _entitySystemManager = default!;
    [Dependency] private readonly IEntityManager _entityManager = default!;
    [Dependency] private readonly IResourceManager _resourceManager = default!;
    [Dependency] private readonly IFileDialogManager _fileDialogManager = default!;
    
    private SortedDictionary<DateTime, ChatEntry> _chatEntries = new();
    private readonly Dictionary<EntityUid, (Button, Action<BaseButton.ButtonEventArgs>)> _channelListBtns = [];
    private EntityUid _selectedChannel;
    
    public LobbyUI()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(RootContainer, LayoutPreset.Wide);
        SendButton.OnPressed += SendButtonPressed;
        SendFileButton.OnPressed += SendFileButtonPressed;
    }

    private async void SendFileButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        await using var stream = await _fileDialogManager.OpenFile(new FileDialogFilters(new FileDialogFilters.Group("png")), FileAccess.Read);
        if(stream is null) 
            return;
        using var memoryStream = new MemoryStream();
        await stream.CopyToAsync(memoryStream);
        
        var bytes = memoryStream.ToArray();
        
        _entitySystemManager.GetEntitySystem<ChatSystem>().SendFile(bytes);
    }

    private void SendButtonPressed(BaseButton.ButtonEventArgs obj)
    {
        _entitySystemManager.GetEntitySystem<ChatSystem>().Send(TextField.Text);
        TextField.Clear();
    }

    public void SetListChannels(IEnumerable<EntityUid> channels)
    {
        foreach (var (entUid, (btn,ev)) in _channelListBtns)
        {
            btn.OnPressed -= ev;
        }
        
        ChatSelectContainer.Children.Clear();
        
        foreach (var channel in channels)
        {
            if (!_entityManager.TryGetComponent<ChatChannelComponent>(channel, out var channelComponent))
            {
                Log.Error($"Channel {channel} not found");
                continue;
            }

            Action<BaseButton.ButtonEventArgs> action = btn =>
            {
                if(channel.Equals(_selectedChannel)) 
                    return;
                
                _entitySystemManager.GetEntitySystem<ChatSystem>().SendSelectedChannel(channel);
            };

            var btn = new Button()
            {
                Text = channelComponent.ChannelName, StyleClasses = { "chat-select" }
            };
            btn.OnPressed += action;
            
            _channelListBtns.Add(channel, (btn, action));
            ChatSelectContainer.AddChild(btn);
        }
    }
    
    public void AddMessage(ChatEntry chatEntry)
    {
        _chatEntries.Add(chatEntry.SendTime, chatEntry);
        
        ChatBox.Children.Clear();
        ChatEntry? lastEntry = null;
        foreach (var entry in _chatEntries)
        {
            AddMessageInternal(entry.Value, lastEntry);
            lastEntry = entry.Value;
        }
    }

    private void AddMessageInternal(ChatEntry chatEntry, ChatEntry? lastValue)
    {
        if (chatEntry.Sender is not null &&
            _entityManager.TryGetComponent<UserComponent>(_entityManager.GetEntity(chatEntry.Sender.Value),
                out var userComponent))
        {
            var entry = new ChatEntryControl();
            entry.SetUser(userComponent);
            entry.SetMessage(chatEntry);
            
            if(lastValue != null && lastValue.Sender.Equals(chatEntry.Sender))
                entry.HideChatInfo();
            
            ChatBox.Children.Add(entry);
        }
        else
        {
            var richText = new RichTextLabel();
            richText.SetMessage(FormattedMessage.FromMarkupOrThrow($"[color=#555555]{chatEntry.Message}[/Color]"));
            ChatBox.Children.Add(richText);
        }
    }

    public void Clear()
    {
        ChatBox.Children.Clear();
        _chatEntries.Clear();
    }

    public void SetLocalUsername(string name)
    {
        CurrentUserLabel.Text = "Hello," + name;
    }

    public void SetChannel(EntityUid channelUid)
    {
        if (_channelListBtns.TryGetValue(_selectedChannel, out var oldSelected))
        {
            oldSelected.Item1.Disabled = false;
        }
        
        if (_channelListBtns.TryGetValue(channelUid, out var newChannel))
        {
            newChannel.Item1.Disabled = true;
            _selectedChannel = channelUid;
        }
    }
}